onlineShop/Controllers/Admin/CategoryAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using onlineShop.Areas.Entity;
using onlineShop.Areas.Identity.Data;
using onlineShop.Models;

namespace onlineShop.Controllers.Admin
{
    [Authorize(Roles = "Адмін")]
    public class CategoryAdminController : Controller
    {
        private readonly OnlineShopContext _context;

        public CategoryAdminController(OnlineShopContext context)
        {
            _context = context;
        }

        public ActionResult Categories()
        {
            return View(_context.Category.ToList());
        }

        public ActionResult AddCategory()
        {
            return View();
        }

        public ActionResult EditCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _context.Category.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        public ActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _context.Category.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCategory(Category model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                _context.Category.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Categories");
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCategoryPost(CategoryModel model)
        {
            if (ModelState.IsValid)
            {
                var p = new Category()
                {
                    Id = model.Id,
                    Name = model.Name,
                };
                _context.Category.Update(p);
                _context.SaveChanges();
            }

            return RedirectToAction("Categories");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategoryPost(int? id)
        {
            var obj = _context.Category.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _context.Category.Remove(obj);
            _context.SaveChanges();
            return RedirectToAction("Categories");
        }
    }
}

onlineShop/Views/CategoryAdmin/AddCategory.cshtml
@model onlineShop.Models.CategoryModel 
@{
    ViewData["Title"] = "Додати категорію";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class="fw-bolder fs-5 p-lg-3 ">Додавання категорії</h1>
            </div>
            <form class="text-dark" asp-controller="CategoryAdmin" asp-action="AddCategory">
                <div class="mb-3">
                    <label class="form-label" asp-for="Name">Назва категорії</label>
                    <input type="text" asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div>
                    <button class="btn btn-success" type="submit">Створити</button>
                    <a asp-controller="CategoryAdmin" asp-action="Categories" class="btn text-dark">Назад</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

onlineShop/Views/CategoryAdmin/Categories.cshtml
@using onlineShop.Areas.Entity
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Категорії";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/lib/fontawesome-free/css/all.min.css")" rel="stylesheet" asp-append-version="true"/>
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
	<div class="content-wrapper">
		<div class="border-top border-primary border-4 bg-light table-responsive">
			<div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
				<h1 class="fw-bolder fs-5 p-lg-3 ">Категорії</h1>
				<a asp-controller="CategoryAdmin" asp-action="AddCategory">
					<button class="btn btn-success">
						<i class="fa-sharp fa-solid fa-file-circle-plus"></i>
						<span>Додати категорію</span>
					</button>
				</a>
			</div>
			<table class="text-center table table-striped">
				<thead class="fs-6">
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Назва категорії</th>
					<th scope="col">Змінити</th>
					<th scope="col">Видалити</th>
				</tr>
				</thead>
				<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>@item.Id</td>
						<td>@item.Name</td>
						<td>
							<a asp-controller="CategoryAdmin" asp-action="EditCategory" asp-route-id="@item.Id">
								<button class="btn btn-primary">
									<i class="fa fa-pen"></i>
								</button>
							</a>
						</td>
						<td>
							<a asp-controller="CategoryAdmin" asp-action="DeleteCategory" asp-route-id="@item.Id">
								<button class="btn btn-danger">
									<i class="fa fa-trash"></i>
								</button>
							</a>
						</td>
					</tr>
				}
				</tbody>
			</table>
		</div>
	</div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
}

onlineShop/Views/CategoryAdmin/DeleteCategory.cshtml
@using onlineShop.Areas.Entity
@model Category
@{
    ViewData["Title"] = "Видалити категорію";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class="fw-bolder fs-5 p-lg-3 ">Видалення категорії</h1>
            </div>
            <form class="text-dark" method="post" asp-controller="CategoryAdmin" asp-action="DeleteCategoryPost">
                <input asp-for="Id" hidden/>
                <div class="mb-3 mt-3">
                    <h5 class="mb-2">Ви впевнені що хочете видалити цю категорію?</h5>
                    <label asp-for="Name" class="form-label">Категорія</label>
                    <input type="text" asp-for="Name" disabled class="form-control">
                </div>
                <div class="mb-3 form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="delCheckBox">
                    <label class="form-check-label">Так, я свідомо видаляю цю категорію</label>
                </div>
                <div>
                    <button disabled id="sendFormBtn" class="btn btn-danger" type="submit">
                        Підтвердити
                    </button>
                    <a class="btn text-dark" asp-controller="CategoryAdmin" asp-action="Categories">
                        Скасувати
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
}

onlineShop/Views/CategoryAdmin/EditCategory.cshtml
@using onlineShop.Areas.Entity
@model Category
@{
    ViewData["Title"] = "Змінити категорію";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class=" fw-bolder fs-5 p-lg-3 ">Редагування категорії</h1>
            </div>
            <form class="text-dark" method="post" asp-controller="CategoryAdmin" asp-action="EditCategoryPost">
                <input asp-for="Id" hidden/>
                <div class="mb-3">
                    <label asp-for="Name" class="form-label">Назва категорії</label>
                    <input type="text" asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div>
                    <button class="btn btn-success" type="submit">
                        Зберегти
                    </button>
                    <a class="btn text-dark" asp-controller="CategoryAdmin" asp-action="Categories">
                        Назад
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}