onlineShop/Controllers/Admin/OrderAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using onlineShop.Areas.Identity.Data;

namespace onlineShop.Controllers.Admin
{
    [Authorize(Roles = "Адмін")]
    public class OrderAdminController : Controller
    {
        private readonly OnlineShopContext _context;

        public OrderAdminController(OnlineShopContext context)
        {
            _context = context;
        }

        public ActionResult Orders()
        {
            return View(_context.ShippingDetail.ToList());
        }
        
        public ActionResult DeleteOrder(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var orderFromDb = _context.ShippingDetail.Find(id);
            if (orderFromDb == null)
            {
                return NotFound();
            }
            return View(orderFromDb);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteOrderPost(int? id)
        {
            var orderFromDb = _context.ShippingDetail.Find(id);
            if (orderFromDb == null)
            {
                return NotFound();
            }
            _context.ShippingDetail.Remove(orderFromDb);
            _context.SaveChanges();
            return RedirectToAction("Orders");
        }
        
    }
}

onlineShop/Controllers/Admin/RoleAdminController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using onlineShop.Models;

namespace onlineShop.Controllers.Admin
{
    [Authorize(Roles = "Адмін")]
    public class RoleAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public RoleAdminController(RoleManager<IdentityRole> roleMgr, UserManager<IdentityUser> userMrg)
        {
            _roleManager = roleMgr;
            _userManager = userMrg;
        }
        public IActionResult Roles()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult AddRole()
        {
            return View(new IdentityRole());
        }

        public async Task<IActionResult> DeleteRole(string? id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            var model = new IdentityRole
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole([Required(ErrorMessage = "Таких не знаємо")] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Roles");
            }
            return View(name);
        }
        

        [HttpPost]
        public async Task<IActionResult> DeleteRolePost(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Roles");
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Roles", _roleManager.Roles);
        }
        
        public async Task<IActionResult> UpdateRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nonMembers = new List<IdentityUser>();
            foreach (IdentityUser user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRole(RoleModification model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            NotFound(userId);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            NotFound(userId);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Roles));
            else
                return await UpdateRole(model.RoleId);
        }

    }
}

onlineShop/Controllers/Admin/UserAdminController.cs
#nullable disable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using onlineShop.Areas.Identity.Data;

namespace onlineShop.Controllers.Admin
{
    [Authorize(Roles = "Адмін")]
    public class UserAdminController : Controller
    {
        private readonly OnlineShopContext _context;
        public UserAdminController(OnlineShopContext context)
        {
            _context = context;
        }
        
        public ActionResult Users()
        {
           return View(_context.Users.ToList());
        }
        [HttpGet]
        public ActionResult DeleteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userFromDb = _context.Users.Find(id);
            if (userFromDb == null)
            {
                return NotFound();
            }
            return View(userFromDb);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteUserPost(string id)
        {
            var obj = _context.Users.Find(id);
            var cart = _context.Cart.OrderBy(o => o.Id).LastOrDefault(u => u.CartUserId.Id == id);

            if (obj == null || cart == null)
            {
                return NotFound();
            }

            foreach (var item in _context.ShippingDetail.Where(u => u.UserId == id)) _context.ShippingDetail.Remove(item);

            _context.Cart.Remove(cart);
            _context.Users.Remove(obj);
            _context.SaveChanges();
            return RedirectToAction("Users");
        }

    }
}

onlineShop/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onlineShop.Areas.Entity;
using onlineShop.Areas.Identity.Data;
using onlineShop.Models;

namespace onlineShop.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly OnlineShopContext _context;

        public ShoppingCartController(OnlineShopContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var delivery = GetDelivery();
            if (delivery.IsActive == false)
            {
                return RedirectToAction("Index", "Home");
            }
            var items = _context.CartItem.Select(s => s).Where(w => w.CartId == delivery.Id);
            return View(items);
        }
        
        [HttpGet]
        public IActionResult NewOrder()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult OrderCompleted()
        {
            int lastId = _context.ShippingDetail.Max(v => v.Id);
            var lastOrder = _context.ShippingDetail.Find(lastId);
            return View(lastOrder);
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewOrder(ShippingDetailModel model)
        {
            var currentAccount = _context.Users.FirstOrDefault(u => u.UserName == User.Identity!.Name);
            if (currentAccount != null)
            {
                
                    ShippingDetail sd = new ShippingDetail()
                    {
                        Id = model.Id,
                        CreateDelivery = DateTime.Now,
                        TotalPrice = Calculate(),
                        District = model.District,
                        City = model.City,
                        Address = model.Address,
                        DeliveryType = model.DeliveryType,
                        User = currentAccount,
                        UserId = currentAccount.Id,
                    };
                    _context.ShippingDetail.Add(sd);
                
            }

            var items = _context.CartItem.Where(u => u.Cart.CartUserId == currentAccount);
            
                foreach (var item in _context.CartItem.Where(u => u.Cart.CartUserId == currentAccount))
                {
                    _context.CartItem.Remove(item);
                }

                var delivery = GetDelivery();
            delivery.IsActive = false;
            
            _context.SaveChanges();
            return RedirectToAction("OrderCompleted");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(int id, string operation)
        {
            var item = await _context.CartItem.FirstOrDefaultAsync(i => i.Id == id);
            if (item != null)
            {
                if (operation == "+" ) ++item.Quantity;
                else if (operation == "-") --item.Quantity;
                else return BadRequest("Not valid");
                
                _context.CartItem.Update(item);
            }
            
            await _context.SaveChangesAsync();
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _context.CartItem.FirstOrDefaultAsync(i => i.Id == id);
            if (item != null) _context.CartItem.Remove(item);
            await _context.SaveChangesAsync();
            return Ok();
        }

        private Cart GetDelivery()
        {
            var currentUser = _context.Users.FirstOrDefault(u => u.UserName == User.Identity!.Name);

            return _context.Cart.OrderBy(o => o.Id).LastOrDefault(u => u.CartUserId == currentUser) ?? throw new InvalidOperationException();
        }

        private double Calculate()
        {
            var currentAccount = _context.Users.FirstOrDefault(u => u.UserName == User.Identity!.Name);
            var currentCart = _context.Cart.FirstOrDefault(u => u.CartUserId == currentAccount);
            var totalPrice = 0.0;
            foreach (var item in _context.CartItem.Where(u => currentCart != null && u.CartId == currentCart.Id))
            {
                var sum = item.Price * item.Quantity;
                totalPrice += sum;
            }
            return totalPrice;
        }
        
    }
}

onlineShop/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>@ViewData["Title"] - VYLKA</title>
		<link rel="icon" type="image/x-icon" href="~/images/favicon/favicon.png">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
		@await RenderSectionAsync("CSS", required: false)
	</head>
	<body> 
        <!-- Navbar -->
        <partial name="_NavBar" />

		<main role="main">
            <div class="wrapper">
				<ul class="sidebar navbar-nav">
					<li class="side-nav-title d-flex">
						<div class="d-flex align-items-center">
							<button class="btn text-white" id="sidebarToggle">
								<img src="~/images/admin/sidebarToggle.png" alt="Card image cap">
							</button>
							<h1 class="text-white">Навігація</h1>
						</div>
					</li>
					<li class="nav-item border-bottom">
						<a class="nav-link d-flex justify-content-between"  asp-controller="UserAdmin" asp-action="Users">
							<div class="d-flex align-items-center">
								<img src="~/images/admin/users.png" alt="Card image cap">
								<span>Користувачі</span>
							</div>
							<span class="arrow fw-semibold float-end">></span>
						</a>
					</li>
					<li class="nav-item border-bottom">
						<a class="nav-link d-flex justify-content-between"  asp-controller="ProductAdmin" asp-action="Products">
							<div class="d-flex align-items-center">
								<img src="~/images/admin/products.png" alt="Card image cap">
								<span>Товари</span>
							</div>
							<span class="arrow fw-semibold float-end">></span>
						</a>
					</li>
					<li class="nav-item border-bottom">
						<a class="nav-link d-flex justify-content-between"  asp-controller="OrderAdmin" asp-action="Orders">
							<div class="d-flex align-items-center">
								<img src="~/images/admin/orders.png" alt="Card image cap">
								<span>Замовлення</span>
							</div>
							<span class="arrow fw-semibold float-end">></span>
						</a>
					</li>
					<li class="nav-item border-bottom">
						<a class="nav-link d-flex justify-content-between"  asp-controller="CategoryAdmin" asp-action="Categories">
							<div class="d-flex align-items-center">
								<img src="~/images/admin/categories.png" alt="Card image cap">
								<span>Категорії товарів</span>
							</div>
							<span class="arrow fw-semibold float-end">></span>
						</a>
					</li>
					<li class="nav-item border-bottom">
						<a class="nav-link d-flex justify-content-between" asp-controller="RoleAdmin" asp-action="Roles">
							<div class="d-flex align-items-center">
								<img src="~/images/admin/roles.png" alt="Card image cap">
								<span>Ролі</span>
							</div>
							<span class="arrow fw-semibold float-end">></span>
						</a>
                    </li> 
				</ul>

				@RenderBody()

            </div>
        </main>
	</body>
</html>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

onlineShop/Views/Shared/_AdminPartial.cshtml
@if(User.IsInRole("Адмін")) {
    <li class="nav-item">
        <a class="nav-link" asp-controller="UserAdmin" asp-action="Users">Адмін</a>
    </li> 
}

onlineShop/Views/Shared/_CheckAuthInShopPartial.cshtml
@inject SignInManager<IdentityUser> SignInManager

@section CSS {
    <link href="@Url.Content("~/css/products.css")" rel="stylesheet" asp-append-version="true"/>
}
@if (SignInManager.IsSignedIn(User))
{
    <button class="btn btn-primary button sendToCartBtn">
        Купити
        <img class="iconCartBtn" src=~/images/icons/cartWhite.png alt="В кошик"/>
        <img class="iconTickBtn" src=~/images/icons/tick.png alt="В кошик"/>
    </button>
}
else
{
    <button class="btn btn-primary button" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Купити
        <img class="iconCartBtn" src=~/images/icons/cartWhite.png alt="В кошик"/>
        <img class="iconTickBtn" src=~/images/icons/tick.png alt="В кошик"/>
    </button>
}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="alert alert-warning" role="alert">Будь ласка, увійдіть, щоб продовжити покупки!</div>
    </div>
</div>

onlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>@ViewData["Title"] - VYLKA</title>
		<link rel="icon" type="image/x-icon" href="~/images/favicon/favicon.png">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
		@await RenderSectionAsync("CSS", required: false)
	</head>
	<body> 
        <!-- Navbar -->
        <partial name="_NavBar" />

		<main role="main"> @RenderBody() </main>
	</body>
</html>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

onlineShop/Views/Shared/_NavBar.cshtml
<nav class="custom-navbar navbar navbar-expand-md navbar-dark">
	<div class="container">
		<a asp-controller="Home" asp-action="Index">
			<h5>lab_univ</h5>
		</a>
		<div class="collapse navbar-collapse" id="navbarsFurni">
			<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
				<partial name="_AdminPartial" />
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Товари </a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li>
							<a class="dropdown-item" asp-controller="Products" asp-action="Index" asp-route-id="1">Холодильники</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="Products" asp-action="Index" asp-route-id="2">Телевізори</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="Products" asp-action="Index" asp-route-id="4">Пилососи</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="Products" asp-action="Index" asp-route-id="3">Кондиціонери</a>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
				<li>
					<a class="nav-link" asp-controller="ShoppingCart" asp-action="Index">
						<img src="~/images/icons/cart.png" alt="shopping cart">
					</a>
				</li>
				<partial name="_LoginPartial" />
			</ul>
		</div>
	</div>
</nav>