onlineShop/Controllers/Admin/ProductAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using onlineShop.Areas.Entity;
using onlineShop.Areas.Identity.Data;
using onlineShop.Models;

namespace onlineShop.Controllers.Admin
{
    [Authorize(Roles = "Адмін")]
    public class ProductAdminController : Controller
    {
        private readonly OnlineShopContext _db;
        public ProductAdminController(OnlineShopContext db)
        {
            _db = db;
        }
        public ActionResult Products()
        {
            return View(_db.Product.ToList());
        }
        public ActionResult AddProduct()
        {
            return View();
        }
        
        public ActionResult EditProduct(int? id)
        {
            Product? productFromDb = _db.Product.Find(id);
            if (productFromDb == null)
            {
                return NotFound();
            }
            return View(productFromDb);
        }
        public ActionResult DeleteProduct(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var productFromDb = _db.Product.Find(id);
            if (productFromDb == null)
            {
                return NotFound();
            }
            return View(productFromDb);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProduct(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                Product p = new Product()
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    CategoryId = model.CategoryId
                };
                _db.Product.Add(p);
                _db.SaveChanges();
                return RedirectToAction("Products");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditProductPost(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                Product p = new Product()
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    CategoryId = model.CategoryId
                };
                _db.Product.Update(p);
                _db.SaveChanges();
                
            }
            return RedirectToAction("Products");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProductPost(int? id)
        {
            var obj = _db.Product.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Product.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Products");
        }
    }
}

onlineShop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using onlineShop.Areas.Entity;
using onlineShop.Areas.Identity.Data;

namespace onlineShop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly OnlineShopContext _context;
        public ProductsController(OnlineShopContext db)
        {
            _context = db;
        }
        [HttpGet]
        public IActionResult Index(int id)
        {
            return View(_context.Product.Where(p => p.CategoryId == id));
        }
        
        [HttpPost]
        public IActionResult AddToCart(int id)
        {

            var currentAccount = _context.Users.FirstOrDefault(u => u.UserName == User.Identity!.Name);

            var currentUserCart = _context.Cart.OrderBy(o => o.Id).LastOrDefault(u => u.CartUserId == currentAccount);

            if (currentUserCart.IsActive == false)
            {
                currentUserCart.IsActive = true;
                _context.SaveChanges();
                
            }

            var selectedProduct = _context.Product.FirstOrDefault(p => p.Id == id);

            var item = _context.CartItem.FirstOrDefault(i =>
                currentUserCart != null && i.ProductId == id && i.CartId == currentUserCart.Id);

            if (item == null && selectedProduct!=null && currentUserCart!=null)
            {
                var order = new CartItem()
                {
                    ProductId = selectedProduct.Id,
                    Quantity = 1,
                    Price = selectedProduct.Price,
                    CartId = currentUserCart.Id,
                    Product = selectedProduct,
                    ProductName = selectedProduct.ProductName,
                };
                _context.CartItem.Add(order);
                _context.SaveChanges();
            }
            else
            {
                if (item != null) item.Quantity++;
                _context.SaveChanges();
            }
            return Ok();
        }
    }   
}

onlineShop/Views/ProductAdmin/AddProduct.cshtml
@model ProductModel
@{
    ViewData["Title"] = "Додати категорію";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class=" fw-bolder fs-5 p-lg-3 ">Додавання товару</h1>
            </div>
            <form class="text-dark" asp-controller="ProductAdmin" asp-action="AddProduct">
                <div class="mb-3">
                    <label class="form-label" asp-for="ProductName">Назва</label>
                    <input type="text" asp-for="ProductName" class="form-control"/>
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Description">Опис</label>
                    <input type="text" asp-for="Description" class="form-control"/>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Price">Ціна</label>
                    <input type="number" asp-for="Price" class="form-control"/>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="CategoryId">ID категорії</label>
                    <input type="number" asp-for="CategoryId" class="form-control"/>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div>
                    <button class="btn btn-success" type="submit">
                        Створити
                    </button>
                    <a class="btn text-dark" asp-controller="ProductAdmin" asp-action="Products">
                        Назад
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

onlineShop/Views/ProductAdmin/DeleteProduct.cshtml
@using onlineShop.Areas.Entity
@model Product
@{
    ViewData["Title"] = "Видалити товар";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class="fw-bolder fs-5 p-lg-3 ">Видалення товару</h1>
            </div>
            <form class="text-dark" method="post" asp-controller="ProductAdmin" asp-action="DeleteProductPost">
                <input asp-for="Id" hidden/>
                <div class="mb-3 mt-3">
                    <h5>Ви впевнені що хочете видалити цей товар?</h5>
                    <label asp-for="ProductName" class="form-label">Назва товару</label>
                    <input type="text" asp-for="ProductName" disabled class="form-control">
                </div>
                <div class="mb-3 form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="delCheckBox">
                    <label class="form-check-label">Так, я свідомо видаляю цей товар</label>
                </div>
                <div>
                    <button disabled id="sendFormBtn" class="btn btn-danger" type="submit">
                        Підтвердити
                    </button>
                    <a class="btn text-dark" asp-controller="ProductAdmin" asp-action="Products">
                        Скасувати
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
}

onlineShop/Views/ProductAdmin/EditProduct.cshtml
@model onlineShop.Areas.Entity.Product
@{
    ViewData["Title"] = "Змінити товар";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
    <div class="content-wrapper">
        <div class="border-top border-primary border-4 bg-light table-responsive">
            <div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
                <h1 class="fw-bolder fs-5 p-lg-3 ">Редагування товару</h1>
            </div>
            <form class="text-dark" method="post" asp-controller="ProductAdmin" asp-action="EditProductPost">
                <input asp-for="Id" hidden/>
                <div class="mb-3">
                    <label asp-for="ProductName" class="form-label">Назва товару</label>
                    <input type="text" asp-for="ProductName" class="form-control">
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Description" class="form-label">Опис</label>
                    <input type="text" asp-for="Description" class="form-control">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Price" class="form-label">Ціна</label>
                    <input type="number" asp-for="Price" class="form-control">
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CategoryId" class="form-label">ID категорії</label>
                    <input type="number" asp-for="CategoryId" class="form-control">
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div>
                    <button class="btn btn-success" type="submit">
                        Зберегти
                    </button>
                    <a class="btn text-dark" asp-controller="ProductAdmin" asp-action="Products">
                        Назад
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

onlineShop/Views/ProductAdmin/Products.cshtml
@using onlineShop.Areas.Entity
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Товари";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section CSS {
    <link href="@Url.Content("~/lib/fontawesome-free/css/all.min.css")" rel="stylesheet" asp-append-version="true"/>
    <link href="@Url.Content("~/css/admin.css")" rel="stylesheet" asp-append-version="true"/>
}

<div class="render-content">
	<div class="content-wrapper">
		<div class="border-top border-primary border-4 bg-light table-responsive">
			<div class="bg-table-title text-dark d-flex justify-content-between align-items-center">
				<h1 class=" fw-bolder fs-5 p-lg-3 ">Товари</h1>
				<a asp-controller="ProductAdmin" asp-action="AddProduct">
					<button class="btn btn-success">
						<i class="fa-sharp fa-solid fa-file-circle-plus"></i>
						<span>Додати товар</span>
					</button>
				</a>
			</div>
			<table class="text-center table table-striped">
				<thead class="fs-6">
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Назва</th>
					<th scope="col">Опис</th>
					<th scope="col">Ціна</th>
					<th scope="col">Id категорії</th>
					<th scope="col">Змінити</th>
					<th scope="col">Видалити</th>
				</tr>
				</thead>
				<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>@item.Id</td>
						<td>@item.ProductName</td>
						<td>@item.Description</td>
						<td>@item.Price</td>
						<td>@item.CategoryId</td>
						<td>
							<a asp-controller="ProductAdmin" asp-action="EditProduct" asp-route-id="@item.Id">
								<button class="btn btn-primary">
									<i class="fa fa-pen"></i>
								</button>
							</a>
						</td>
						<td>
							<a asp-controller="ProductAdmin" asp-action="DeleteProduct" asp-route-id="@item.Id">
								<button class="btn btn-danger">
									<i class="fa fa-trash"></i>
								</button>
							</a>
						</td>
					</tr>
				}
				</tbody>
			</table>
		</div>
	</div>
</div>
@section Scripts {
    <script src="@Url.Content("~/js/admin.js")" asp-append-version="true"></script>
}